server:
  port: 8091
  tomcat:
    max-threads: 200
spring:
  application:
    name: order-service
  zipkin:
    base-url: http://127.0.0.1:9411/ #zipkin server的请求地址
    discoveryClientEnabled: false #让nacos把它当成一个URL，而不要当做服务名
    sleuth:
      sampler:
        probability: 1.0 #采样的百分比
  datasource:
    #type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.89.210.180:3306/caocao?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:7070 # 指定控制台服务的地址
        port: 9999 #跟控制台交流的端口,随意指定一个未使用的端口即可
      eager: true
rocketmq:
  name-server: localhost:9876 #rocketMQ服务的地址
  producer:
    group: ${spring.application.name} # 生产者组
logging:
  config: classpath:logback-spring.xml
feign:
  sentinel:
    enabled: true
ribbon:
  eager-load:
    enabled: true
